apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: owmdx3xjb-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: owmdx3xjb-python 
  name: owmdx3xjb-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: owmdx3xjb-python 
